/**
 * transitionLibrary.ts
 * Built-in transition scene templates.
 *
 * All 14 templates use existing widget types — no new widget components required.
 * These are read-only. Users duplicate them to create editable copies.
 *
 * Widget positioning uses 1920x1080 coordinate space (matching CANVAS_W x CANVAS_H).
 * Widget entry animations use the existing SceneWidget.animation system.
 */

import type { TransitionScene } from './types';

const makeId = (prefix: string) => `tpl-${prefix}-${Math.random().toString(36).slice(2, 8)}`;

const baseWidget = {
  rotation: 0,
  scale: 1,
  locked: false,
  visible: true,
  groupId: undefined,
  colorLabel: undefined,
  expanded: false,
  style: {},
  animation: { type: 'none' as const, duration: 0.5, delay: 0, loop: false },
  content: { type: '', settings: {} },
};

// ─── Template Definitions ─────────────────────────────────────────────────────

export const TRANSITION_LIBRARY: TransitionScene[] = [

  // 1. Camera Flash ─────────────────────────────────────────────────────────────
  {
    id: makeId('camera-flash'),
    name: 'Camera Flash',
    description: 'Clean white flash that covers the screen and fades out on the new scene.',
    category: 'Minimal',
    duration: 500,
    switchMarker: 200,
    easing: 'ease-in-out',
    tags: ['flash', 'white', 'minimal', 'clean'],
    isTemplate: true,
    keyframes: [],
    widgets: [
      {
        ...baseWidget,
        id: makeId('flash-bg'),
        type: 'background',
        label: 'Flash',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 1,
        style: { background: '#ffffff' },
        animation: { type: 'fade', duration: 0.2, delay: 0, loop: false },
        content: { type: 'background', settings: { color: '#ffffff' } },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // 2. Minimal Slide ─────────────────────────────────────────────────────────────
  {
    id: makeId('minimal-slide'),
    name: 'Minimal Slide',
    description: 'A sleek dark panel sweeps across the screen between scenes.',
    category: 'Minimal',
    duration: 600,
    switchMarker: 300,
    easing: 'ease-in-out',
    tags: ['slide', 'minimal', 'dark', 'clean'],
    isTemplate: true,
    keyframes: [],
    widgets: [
      {
        ...baseWidget,
        id: makeId('slide-bg'),
        type: 'background',
        label: 'Slide Panel',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 1,
        style: { background: 'linear-gradient(135deg, #0c0a1a, #1a0a2e)' },
        animation: { type: 'slide-left', duration: 0.3, delay: 0, loop: false },
        content: { type: 'background', settings: {} },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // 3. Logo Swoosh ────────────────────────────────────────────────────────────────
  {
    id: makeId('logo-swoosh'),
    name: 'Logo Swoosh',
    description: 'Your logo sweeps across the screen from left to right during the transition.',
    category: 'Logo',
    duration: 800,
    switchMarker: 450,
    easing: 'ease-in-out',
    tags: ['logo', 'swoosh', 'energetic', 'brand'],
    isTemplate: true,
    keyframes: [
      { time: 0,   widgetId: 'logo-main', property: 'x',       value: -400,  easing: 'ease-in' },
      { time: 400, widgetId: 'logo-main', property: 'x',       value: 960,   easing: 'ease-in-out' },
      { time: 800, widgetId: 'logo-main', property: 'x',       value: 2300,  easing: 'ease-out' },
      { time: 0,   widgetId: 'logo-main', property: 'opacity', value: 100,   easing: 'linear' },
      { time: 700, widgetId: 'logo-main', property: 'opacity', value: 100,   easing: 'linear' },
      { time: 800, widgetId: 'logo-main', property: 'opacity', value: 0,     easing: 'ease-in' },
    ],
    widgets: [
      {
        ...baseWidget,
        id: makeId('swoosh-bg'),
        type: 'background',
        label: 'Dark BG',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 1,
        style: { background: 'linear-gradient(135deg, #0c0a1a 0%, #1a1040 100%)' },
        animation: { type: 'fade', duration: 0.15, delay: 0, loop: false },
        content: { type: 'background', settings: {} },
      },
      {
        ...baseWidget,
        id: 'logo-main',
        type: 'logo',
        label: 'Swoosh Logo',
        x: -400, y: 390, width: 400, height: 300,
        opacity: 100, zIndex: 10,
        style: {},
        animation: { type: 'none', duration: 0.5, delay: 0, loop: false },
        content: { type: 'logo', settings: { text: 'VibeOverlay', fontSize: 64 } },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // 4. Neon Reveal ────────────────────────────────────────────────────────────────
  {
    id: makeId('neon-reveal'),
    name: 'Neon Reveal',
    description: 'Neon accent lines sweep across the screen revealing the new scene with electric energy.',
    category: 'Energetic',
    duration: 700,
    switchMarker: 350,
    easing: 'ease-in-out',
    tags: ['neon', 'reveal', 'esports', 'lines', 'energetic'],
    isTemplate: true,
    keyframes: [],
    widgets: [
      {
        ...baseWidget,
        id: makeId('neon-bg'),
        type: 'background',
        label: 'Dark BG',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 1,
        style: { background: '#050310' },
        animation: { type: 'fade', duration: 0.1, delay: 0, loop: false },
        content: { type: 'background', settings: {} },
      },
      {
        ...baseWidget,
        id: makeId('neon-line-1'),
        type: 'shape',
        label: 'Neon Line 1',
        x: 0, y: 520, width: 1920, height: 4,
        opacity: 100, zIndex: 5,
        style: { background: '#a855f7', glowColor: '#a855f7', glowBlur: 20 },
        animation: { type: 'slide-left', duration: 0.3, delay: 0, loop: false },
        content: { type: 'shape', settings: { shape: 'rectangle' } },
      },
      {
        ...baseWidget,
        id: makeId('neon-line-2'),
        type: 'shape',
        label: 'Neon Line 2',
        x: 0, y: 556, width: 1920, height: 2,
        opacity: 70, zIndex: 5,
        style: { background: '#5cffe2', glowColor: '#5cffe2', glowBlur: 12 },
        animation: { type: 'slide-left', duration: 0.3, delay: 0.05, loop: false },
        content: { type: 'shape', settings: { shape: 'rectangle' } },
      },
      {
        ...baseWidget,
        id: makeId('neon-glow'),
        type: 'glow-effect',
        label: 'Center Glow',
        x: 760, y: 440, width: 400, height: 200,
        opacity: 60, zIndex: 3,
        style: { background: 'radial-gradient(ellipse, rgba(168,85,247,0.4) 0%, transparent 70%)' },
        animation: { type: 'scale', duration: 0.4, delay: 0.1, loop: false },
        content: { type: 'glow-effect', settings: {} },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // 5. Energy Burst ───────────────────────────────────────────────────────────────
  {
    id: makeId('energy-burst'),
    name: 'Energy Burst',
    description: 'A radial burst of energy from the center — great for high-energy scene transitions.',
    category: 'Energetic',
    duration: 600,
    switchMarker: 300,
    easing: 'ease-out',
    tags: ['burst', 'energy', 'particles', 'radial', 'esports'],
    isTemplate: true,
    keyframes: [],
    widgets: [
      {
        ...baseWidget,
        id: makeId('burst-bg'),
        type: 'background',
        label: 'Dark BG',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 1,
        style: { background: 'radial-gradient(ellipse at center, #1a0840 0%, #050310 100%)' },
        animation: { type: 'fade', duration: 0.1, delay: 0, loop: false },
        content: { type: 'background', settings: {} },
      },
      {
        ...baseWidget,
        id: makeId('burst-glow-1'),
        type: 'glow-effect',
        label: 'Inner Burst',
        x: 610, y: 190, width: 700, height: 700,
        opacity: 100, zIndex: 5,
        style: { background: 'radial-gradient(ellipse, rgba(168,85,247,0.9) 0%, rgba(168,85,247,0.2) 40%, transparent 70%)' },
        animation: { type: 'scale', duration: 0.3, delay: 0, loop: false },
        content: { type: 'glow-effect', settings: {} },
      },
      {
        ...baseWidget,
        id: makeId('burst-glow-2'),
        type: 'glow-effect',
        label: 'Outer Burst',
        x: 410, y: -10, width: 1100, height: 1100,
        opacity: 60, zIndex: 4,
        style: { background: 'radial-gradient(ellipse, rgba(92,255,226,0.4) 0%, transparent 60%)' },
        animation: { type: 'scale', duration: 0.4, delay: 0.05, loop: false },
        content: { type: 'glow-effect', settings: {} },
      },
      {
        ...baseWidget,
        id: makeId('burst-particles'),
        type: 'particles',
        label: 'Particles',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 80, zIndex: 6,
        style: { background: 'transparent' },
        animation: { type: 'fade', duration: 0.3, delay: 0, loop: false },
        content: { type: 'particles', settings: {} },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // 6. Glitch ─────────────────────────────────────────────────────────────────────
  {
    id: makeId('glitch'),
    name: 'Glitch',
    description: 'Digital glitch distortion flickers across the screen between scenes.',
    category: 'Glitch',
    duration: 500,
    switchMarker: 250,
    easing: 'linear',
    tags: ['glitch', 'digital', 'cyber', 'distortion'],
    isTemplate: true,
    keyframes: [],
    widgets: [
      {
        ...baseWidget,
        id: makeId('glitch-bg'),
        type: 'background',
        label: 'Glitch BG',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 1,
        style: { background: '#050310' },
        animation: { type: 'fade', duration: 0.1, delay: 0, loop: false },
        content: { type: 'background', settings: {} },
      },
      {
        ...baseWidget,
        id: makeId('glitch-r'),
        type: 'shape',
        label: 'Glitch R',
        x: 3, y: 0, width: 1920, height: 360,
        opacity: 40, zIndex: 3,
        style: { background: 'rgba(239,68,68,0.3)', blendMode: 'screen' },
        animation: { type: 'shake', duration: 0.25, delay: 0, loop: false },
        content: { type: 'shape', settings: { shape: 'rectangle' } },
      },
      {
        ...baseWidget,
        id: makeId('glitch-b'),
        type: 'shape',
        label: 'Glitch B',
        x: -3, y: 360, width: 1920, height: 360,
        opacity: 40, zIndex: 3,
        style: { background: 'rgba(59,130,246,0.3)', blendMode: 'screen' },
        animation: { type: 'shake', duration: 0.25, delay: 0.04, loop: false },
        content: { type: 'shape', settings: { shape: 'rectangle' } },
      },
      {
        ...baseWidget,
        id: makeId('glitch-g'),
        type: 'shape',
        label: 'Glitch G',
        x: 0, y: 720, width: 1920, height: 360,
        opacity: 40, zIndex: 3,
        style: { background: 'rgba(16,185,129,0.3)', blendMode: 'screen' },
        animation: { type: 'shake', duration: 0.25, delay: 0.08, loop: false },
        content: { type: 'shape', settings: { shape: 'rectangle' } },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // 7. Cyber Portal ───────────────────────────────────────────────────────────────
  {
    id: makeId('cyber-portal'),
    name: 'Cyber Portal',
    description: 'A neon ring expands outward consuming the screen, then collapses to reveal the destination.',
    category: 'Esports',
    duration: 900,
    switchMarker: 500,
    easing: 'ease-in-out',
    tags: ['portal', 'neon', 'cyber', 'ring', 'esports'],
    isTemplate: true,
    keyframes: [],
    widgets: [
      {
        ...baseWidget,
        id: makeId('portal-bg'),
        type: 'background',
        label: 'Portal BG',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 1,
        style: { background: 'radial-gradient(ellipse at center, #1a0840 0%, #050310 100%)' },
        animation: { type: 'fade', duration: 0.15, delay: 0, loop: false },
        content: { type: 'background', settings: {} },
      },
      {
        ...baseWidget,
        id: makeId('portal-ring-outer'),
        type: 'shape',
        label: 'Portal Ring',
        x: 710, y: 340, width: 500, height: 400,
        opacity: 100, zIndex: 5,
        style: {
          background: 'transparent',
          borderSize: 3,
          borderColor: '#a855f7',
          borderRadius: 999,
          glowColor: '#a855f7',
          glowBlur: 30,
        },
        animation: { type: 'scale', duration: 0.5, delay: 0, loop: false },
        content: { type: 'shape', settings: { shape: 'ellipse' } },
      },
      {
        ...baseWidget,
        id: makeId('portal-inner-glow'),
        type: 'glow-effect',
        label: 'Portal Core',
        x: 760, y: 390, width: 400, height: 300,
        opacity: 80, zIndex: 4,
        style: { background: 'radial-gradient(ellipse, rgba(168,85,247,0.8) 0%, transparent 70%)' },
        animation: { type: 'scale', duration: 0.5, delay: 0.1, loop: false },
        content: { type: 'glow-effect', settings: {} },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // 8. Glass Wipe ─────────────────────────────────────────────────────────────────
  {
    id: makeId('glass-wipe'),
    name: 'Glass Wipe',
    description: 'A frosted glass panel slides across, wiping from one scene to the next.',
    category: 'Cinematic',
    duration: 700,
    switchMarker: 350,
    easing: 'ease-in-out',
    tags: ['glass', 'wipe', 'cinematic', 'frosted'],
    isTemplate: true,
    keyframes: [],
    widgets: [
      {
        ...baseWidget,
        id: makeId('glass-panel'),
        type: 'glass-panel',
        label: 'Glass Wipe Panel',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 90, zIndex: 5,
        style: { background: 'rgba(255,255,255,0.08)', glassEffect: true, borderRadius: 0 },
        animation: { type: 'slide-left', duration: 0.35, delay: 0, loop: false },
        content: { type: 'glass-panel', settings: {} },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // 9. Esports Reveal ─────────────────────────────────────────────────────────────
  {
    id: makeId('esports-reveal'),
    name: 'Esports Reveal',
    description: 'Cinematic dark panel with accent bars and logo reveal — high-production esports style.',
    category: 'Esports',
    duration: 800,
    switchMarker: 450,
    easing: 'ease-in-out',
    tags: ['esports', 'reveal', 'bars', 'logo', 'cinematic'],
    isTemplate: true,
    keyframes: [],
    widgets: [
      {
        ...baseWidget,
        id: makeId('esports-bg'),
        type: 'background',
        label: 'Dark BG',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 1,
        style: { background: 'linear-gradient(180deg, #0c0a1a 0%, #05030f 100%)' },
        animation: { type: 'fade', duration: 0.1, delay: 0, loop: false },
        content: { type: 'background', settings: {} },
      },
      {
        ...baseWidget,
        id: makeId('esports-bar-top'),
        type: 'shape',
        label: 'Top Bar',
        x: 0, y: 0, width: 1920, height: 6,
        opacity: 100, zIndex: 5,
        style: { background: 'linear-gradient(90deg, #a855f7, #5cffe2)', glowColor: '#a855f7', glowBlur: 12 },
        animation: { type: 'slide-left', duration: 0.3, delay: 0, loop: false },
        content: { type: 'shape', settings: { shape: 'rectangle' } },
      },
      {
        ...baseWidget,
        id: makeId('esports-bar-bot'),
        type: 'shape',
        label: 'Bottom Bar',
        x: 0, y: 1074, width: 1920, height: 6,
        opacity: 100, zIndex: 5,
        style: { background: 'linear-gradient(90deg, #5cffe2, #a855f7)', glowColor: '#5cffe2', glowBlur: 12 },
        animation: { type: 'slide-left', duration: 0.3, delay: 0.05, loop: false },
        content: { type: 'shape', settings: { shape: 'rectangle' } },
      },
      {
        ...baseWidget,
        id: makeId('esports-logo'),
        type: 'logo',
        label: 'Channel Logo',
        x: 760, y: 440, width: 400, height: 200,
        opacity: 100, zIndex: 10,
        style: { fontColor: '#ffffff', fontSize: 48, fontWeight: '800' },
        animation: { type: 'scale', duration: 0.4, delay: 0.1, loop: false },
        content: { type: 'logo', settings: { text: 'VibeOverlay' } },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // 10. Lightning Strike ───────────────────────────────────────────────────────────
  {
    id: makeId('lightning-strike'),
    name: 'Lightning Strike',
    description: 'Blinding flash followed by an electric burst — intense and dramatic.',
    category: 'Energetic',
    duration: 600,
    switchMarker: 200,
    easing: 'ease-out',
    tags: ['lightning', 'flash', 'electric', 'dramatic', 'intense'],
    isTemplate: true,
    keyframes: [],
    widgets: [
      {
        ...baseWidget,
        id: makeId('lightning-flash'),
        type: 'background',
        label: 'Flash',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 2,
        style: { background: '#ffffff' },
        animation: { type: 'fade', duration: 0.15, delay: 0, loop: false },
        content: { type: 'background', settings: {} },
      },
      {
        ...baseWidget,
        id: makeId('lightning-burst'),
        type: 'glow-effect',
        label: 'Electric Burst',
        x: 560, y: 140, width: 800, height: 800,
        opacity: 90, zIndex: 5,
        style: { background: 'radial-gradient(ellipse, rgba(92,255,226,0.9) 0%, rgba(168,85,247,0.4) 30%, transparent 70%)' },
        animation: { type: 'scale', duration: 0.3, delay: 0.15, loop: false },
        content: { type: 'glow-effect', settings: {} },
      },
      {
        ...baseWidget,
        id: makeId('lightning-bg-dark'),
        type: 'background',
        label: 'Dark Overlay',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 80, zIndex: 1,
        style: { background: '#050310' },
        animation: { type: 'fade', duration: 0.2, delay: 0.1, loop: false },
        content: { type: 'background', settings: {} },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // 11. Anime Slash ────────────────────────────────────────────────────────────────
  {
    id: makeId('anime-slash'),
    name: 'Anime Slash',
    description: 'A dramatic diagonal slash wipe across the screen — anime/manga style transition.',
    category: 'Anime',
    duration: 500,
    switchMarker: 250,
    easing: 'ease-in',
    tags: ['anime', 'slash', 'diagonal', 'manga', 'dramatic'],
    isTemplate: true,
    keyframes: [],
    widgets: [
      {
        ...baseWidget,
        id: makeId('slash-bg'),
        type: 'background',
        label: 'Slash BG',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 1,
        style: { background: '#ffffff' },
        animation: { type: 'fade', duration: 0.1, delay: 0, loop: false },
        content: { type: 'background', settings: {} },
      },
      {
        ...baseWidget,
        id: makeId('slash-line-1'),
        type: 'shape',
        label: 'Slash Line',
        x: -100, y: 0, width: 2200, height: 8,
        rotation: 15,
        opacity: 100, zIndex: 5,
        style: { background: '#a855f7', glowColor: '#a855f7', glowBlur: 16 },
        animation: { type: 'slide-left', duration: 0.25, delay: 0, loop: false },
        content: { type: 'shape', settings: { shape: 'rectangle' } },
      },
      {
        ...baseWidget,
        id: makeId('slash-line-2'),
        type: 'shape',
        label: 'Slash Line 2',
        x: -100, y: 0, width: 2200, height: 3,
        rotation: 15,
        opacity: 60, zIndex: 4,
        style: { background: '#5cffe2', glowColor: '#5cffe2', glowBlur: 8 },
        animation: { type: 'slide-left', duration: 0.25, delay: 0.03, loop: false },
        content: { type: 'shape', settings: { shape: 'rectangle' } },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // 12. Logo Spin ──────────────────────────────────────────────────────────────────
  {
    id: makeId('logo-spin'),
    name: 'Logo Spin',
    description: 'Your logo spins and scales from nothing to fill the screen, then recedes.',
    category: 'Logo',
    duration: 900,
    switchMarker: 500,
    easing: 'ease-in-out',
    tags: ['logo', 'spin', 'scale', 'brand'],
    isTemplate: true,
    keyframes: [
      { time: 0,   widgetId: 'spin-logo', property: 'scale',   value: 0,   easing: 'ease-in' },
      { time: 400, widgetId: 'spin-logo', property: 'scale',   value: 1.2, easing: 'ease-out' },
      { time: 500, widgetId: 'spin-logo', property: 'scale',   value: 1,   easing: 'ease-in-out' },
      { time: 800, widgetId: 'spin-logo', property: 'scale',   value: 0,   easing: 'ease-in' },
      { time: 0,   widgetId: 'spin-logo', property: 'opacity', value: 0,   easing: 'linear' },
      { time: 100, widgetId: 'spin-logo', property: 'opacity', value: 100, easing: 'linear' },
      { time: 750, widgetId: 'spin-logo', property: 'opacity', value: 100, easing: 'linear' },
      { time: 900, widgetId: 'spin-logo', property: 'opacity', value: 0,   easing: 'ease-in' },
    ],
    widgets: [
      {
        ...baseWidget,
        id: makeId('spin-bg'),
        type: 'background',
        label: 'Spin BG',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 1,
        style: { background: 'radial-gradient(ellipse at center, #1a0840, #050310)' },
        animation: { type: 'fade', duration: 0.15, delay: 0, loop: false },
        content: { type: 'background', settings: {} },
      },
      {
        ...baseWidget,
        id: 'spin-logo',
        type: 'logo',
        label: 'Spinning Logo',
        x: 760, y: 440, width: 400, height: 200,
        opacity: 0, zIndex: 10,
        style: { fontColor: '#ffffff', fontSize: 56, fontWeight: '800' },
        animation: { type: 'spin', duration: 0.5, delay: 0, loop: true },
        content: { type: 'logo', settings: { text: 'VibeOverlay' } },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // 13. Smoke Reveal ────────────────────────────────────────────────────────────────
  {
    id: makeId('smoke-reveal'),
    name: 'Smoke Reveal',
    description: 'Layered dark panels with differing opacities create a smoky reveal effect.',
    category: 'Cinematic',
    duration: 800,
    switchMarker: 400,
    easing: 'ease-in-out',
    tags: ['smoke', 'reveal', 'cinematic', 'layers', 'dark'],
    isTemplate: true,
    keyframes: [],
    widgets: [
      {
        ...baseWidget,
        id: makeId('smoke-1'),
        type: 'background',
        label: 'Smoke Layer 1',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 3,
        style: { background: 'rgba(5,3,16,0.95)' },
        animation: { type: 'fade', duration: 0.4, delay: 0, loop: false },
        content: { type: 'background', settings: {} },
      },
      {
        ...baseWidget,
        id: makeId('smoke-2'),
        type: 'background',
        label: 'Smoke Layer 2',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 70, zIndex: 2,
        style: { background: 'linear-gradient(45deg, rgba(26,8,64,0.8), rgba(12,10,26,0.8))' },
        animation: { type: 'fade', duration: 0.5, delay: 0.05, loop: false },
        content: { type: 'background', settings: {} },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // 14. Fire Wipe ────────────────────────────────────────────────────────────────────
  {
    id: makeId('fire-wipe'),
    name: 'Fire Wipe',
    description: 'An orange-red gradient wipe blazes across the screen.',
    category: 'Energetic',
    duration: 650,
    switchMarker: 325,
    easing: 'ease-in-out',
    tags: ['fire', 'wipe', 'orange', 'hot', 'energetic'],
    isTemplate: true,
    keyframes: [],
    widgets: [
      {
        ...baseWidget,
        id: makeId('fire-bg'),
        type: 'background',
        label: 'Fire BG',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 1,
        style: { background: 'linear-gradient(135deg, #1a0505 0%, #3d0000 100%)' },
        animation: { type: 'fade', duration: 0.1, delay: 0, loop: false },
        content: { type: 'background', settings: {} },
      },
      {
        ...baseWidget,
        id: makeId('fire-wipe-panel'),
        type: 'shape',
        label: 'Fire Panel',
        x: 0, y: 0, width: 1920, height: 1080,
        opacity: 100, zIndex: 3,
        style: { background: 'linear-gradient(90deg, #dc2626, #f97316, #fbbf24)' },
        animation: { type: 'slide-left', duration: 0.325, delay: 0, loop: false },
        content: { type: 'shape', settings: { shape: 'rectangle' } },
      },
      {
        ...baseWidget,
        id: makeId('fire-glow'),
        type: 'glow-effect',
        label: 'Fire Glow',
        x: 560, y: 140, width: 800, height: 800,
        opacity: 60, zIndex: 4,
        style: { background: 'radial-gradient(ellipse, rgba(251,191,36,0.5) 0%, transparent 70%)' },
        animation: { type: 'scale', duration: 0.3, delay: 0.1, loop: false },
        content: { type: 'glow-effect', settings: {} },
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

];

// ─── Helper ───────────────────────────────────────────────────────────────────

/** Get a transition template by ID */
export function getTransitionTemplate(id: string): TransitionScene | undefined {
  return TRANSITION_LIBRARY.find(t => t.id === id);
}

/** Get all templates in a category */
export function getTemplatesByCategory(category: string): TransitionScene[] {
  return TRANSITION_LIBRARY.filter(t => t.category === category);
}
